[build]
  publish = ""
  command = ""

[[headers]]
  for = "/image/map/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/image/digimon/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/image/digimon/**/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

    [[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/app/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301